name: TerraTest
on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2

      - name: Validate emerald-triangle
        run: |
          cd emerald-triangle
          terraform init -backend=false
          terraform validate
          tflint --init
          tflint

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: emerald-triangle

  terratest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests
    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: s3,dynamodb,iam,sts,ec2,vpc,route53,cloudwatch,config,kms,logs
          DEBUG: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.x'

      - name: Copy mock provider for stack
        run: |
          cp mocks/mock_provider.tf ../emerald-triangle/

      - name: Run Terratest
        run: go test -v -timeout 30m
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-west-2
          AWS_ENDPOINT_URL: http://localhost:4566
